// levels.js — mondes & niveaux (level design original).
// Légende des tuiles:
//  ' ' vide | X sol | H bloc dur | B brique | ? bloc(pièce) | M bloc(power-up) | U bloc(étoile)
//  p corps de tuyau | P tête de tuyau | ^ pics | = plateforme | o pièce | G arrivée
//  T ressort | C checkpoint | j gemme cachée | m plateforme mobile (horiz.) | n plateforme mobile (vert.)
//  S départ joueur | g marcheur | k ennemi à carapace | f volant | z ennemi à pics | O boss

export const WORLDS = [
  {
    name: 'Plaines de Bolt',
    levels: [
      {
        name: '1-1 Premiers pas', theme: 'overworld', time: 300,
        map: [
          '                                                                                            ',
          '                                                                                            ',
          '          o o o                            o o                                              ',
          '                        ?                 ?  ?              j           o o o                ',
          '                                                          P                                  ',
          '            ?  B?B           o o          BB?BB          pp        BMB                       ',
          '                                  g                      pp                                  ',
          '                       g                          g      pp           f                     ',
          '                  ===            ^^          g           pp                   o o o          ',
          'S        g                  XXX      XXX           XXX   pp        g    g                  G ',
          'XXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
          'XXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        ],
      },
      {
        name: '1-2 Cavernes', theme: 'underground', time: 300,
        map: [
          'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
          'H                                                                                     H',
          'H   o o      B?B          o o o            BBBB          k                             H',
          'H            BBB                                                       o o             H',
          'H                     ===           f           ===          === ?                    H',
          'H    g          o o          ^^^          k            g                      P        H',
          'H        ===   XXXX    g           XX          ===          XXX      g        p   o o  H',
          'HS    XX                    XXX        XXXXX            ===      ^^^           p      G H',
          'HXXXXXXX   XXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXX  XXXXXXXXXX  XXXXXXXXXXXXXH',
          'HXXXXXXX   XXXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXX  XXXXXXXXXX  XXXXXXXXXXXXXH',
          'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
          'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
        ],
      },
      {
        name: '1-3 Collines fleuries', theme: 'overworld', time: 320,
        map: [
          '                                                                              ',
          '            j                          o o o                      j            ',
          '         =====                                                 ======          ',
          '                        ?        BB?BB              ?                          ',
          '   ?              o o                       o o            M                   ',
          '          ===            f          ===                        ===            ',
          '                                                                              ',
          '                                                                              ',
          '       C                                                            C         ',
          '  S   g    ^^^   k      ^^^   g     g k   ^^^   g    k   ^^^    g           G  ',
          'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
          'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        ],
      },
    ],
  },
  {
    name: 'Forteresse',
    levels: [
      {
        name: '2-1 Remparts', theme: 'overworld', time: 320,
        map: [
          '                                                                                                 ',
          '                                                                                                 ',
          '              o o o o                          MBM                       o o o o                 ',
          '          ?                  BB?BB                          f f                                  ',
          '                    f                    o o                          === L      U              ',
          '       ===       o o     ===        ===           ^^^^         ===            o o      ===       ',
          '                              k             g            k                g              g       ',
          '   S      g            g            ^^^            XXX           g    ^^^^         g            G ',
          '  XXXXXXX     XXXXXX  XXXXXXX   XXXXXXXXXXX     XXXXXXXXX   XXXXXXX  XXXXXXXXXX  XXXXXXX  XXXXXXXXX',
          '  XXXXXXX     XXXXXX  XXXXXXX   XXXXXXXXXXX     XXXXXXXXX   XXXXXXX  XXXXXXXXXX  XXXXXXX  XXXXXXXXX',
          'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
          'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        ],
      },
      {
        name: '2-2 Château', theme: 'castle', time: 320,
        map: [
          'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
          'H                                                                                          H',
          'H      o o       BMB             k k            ===           B?B           o o o           H',
          'H   ?         ===          ^^^          ===            f            ===              ?      H',
          'H        f             o o       k            ^^^^           k k          f         o o     H',
          'H   ===        ^^^           ===        XXXX          ===          ^^^^        ===          H',
          'HS        k          ^^^^          k           g            ^^^           k            k  G H',
          'HXXXX   XXXXX   XXXXXX    XXXX   XXXXXXX   XXXX     XXXXXX  XXXX    XXXXXX   XXXX   XXXXXXXXXXH',
          'HXXXX   XXXXX   XXXXXX    XXXX   XXXXXXX   XXXX     XXXXXX  XXXX    XXXXXX   XXXX   XXXXXXXXXXH',
          'HXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXH',
          'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
          'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
        ],
      },
      {
        name: '2-3 Souterrain profond', theme: 'underground', time: 320,
        map: [
          'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
          'H        j                      o o o                      j            H',
          'H    ===          B?B                      ===                  ===     H',
          'H                                                                      H',
          'H   o o      ===                 ===            m          ===     U    H',
          'H        z          ^^^               ^^^            z                 H',
          'H  C   XXXX     g        XXXX    k        XXXX    g       XXXXX    C    H',
          'HS    XX                                                       XX     GH',
          'HXXXXXXX   XXXXXXXXX  XXXXXXXXXX   XXXXXXXX   XXXXXXXXX  XXXXXXXXXXXXXXXH',
          'HXXXXXXX   XXXXXXXXX  XXXXXXXXXX   XXXXXXXX   XXXXXXXXX  XXXXXXXXXXXXXXXH',
          'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
          'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
        ],
      },
    ],
  },
  {
    name: 'Cimes & Gardien',
    levels: [
      {
        name: '3-1 Cimes venteuses', theme: 'overworld', time: 340,
        map: [
          '                                                                             ',
          '           j                       j                        j                 ',
          '        =====                   =======                  ======               ',
          '                                                                             ',
          '              U                                                              ',
          '   ?                  o o          ?                 o o          ?           ',
          '                ====                    ====                ===              ',
          '                                                                             ',
          '              m            C          n                                      ',
          '  S   g     z   T  g         z      g   T   z    g       g      g     G       ',
          'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
          'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        ],
      },
      {
        name: '3-2 Pont des cieux', theme: 'overworld', time: 340,
        map: [
          '                                                                            ',
          '       j                  o o o                  j                            ',
          '    ======                              ======                               ',
          '                  M              U                          ?                ',
          '           ===          ===           ===          ===                       ',
          '   ?                              o o                               ?         ',
          '              n            m            n             m                      ',
          '                                                                            ',
          '              C                                       C                      ',
          '  S   g  T  z      g       z      g    z  T  z    g       g      g     G       ',
          'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
          'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        ],
      },
      {
        name: "3-3 Antre du Gardien", theme: 'castle', time: 200,
        map: [
          'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
          'H                                          H',
          'H    M                                M     H',
          'H                                          H',
          'H        ===                  ===          H',
          'H                                          H',
          'H            j                    j        H',
          'H   ===                            ===     H',
          'H                                          H',
          'H S            o o      O      o o         H',
          'HXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXH',
          'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
        ],
      },
    ],
  },
];

// Arènes versus (symétriques, bouclées par les bords)
export const ARENAS = [
  {
    name: 'Arène Duo', theme: 'overworld', time: 99,
    map: [
      '                                        ',
      '                                        ',
      '       ?              MM             ?   ',
      '                                        ',
      '    ====        ========        ====    ',
      '                                        ',
      '         o o                 o o        ',
      '   1                                2   ',
      '======        ==========        ========',
      '                                        ',
      '         ====            ====           ',
      'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ],
  },
  {
    name: 'Tours', theme: 'castle', time: 99,
    map: [
      '                                        ',
      '   ==                            ==     ',
      '   ==        MM      MM           ==     ',
      '   ==                             ==     ',
      '        ====            ====             ',
      '   1                                2    ',
      '  =====                        =======   ',
      '              ==========                 ',
      '       o o                    o o        ',
      '   =======                    =======    ',
      '                                         ',
      'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ],
  },
  {
    name: 'Ressorts', theme: 'overworld', time: 99,
    map: [
      '                                        ',
      '                                        ',
      '      MM                       MM        ',
      '   ====                           ====   ',
      '                                        ',
      '   1          ========          2        ',
      '  ===                            ===     ',
      '            T            T               ',
      '       ====                ====          ',
      '                                        ',
      '   o o      ====    ====     o o         ',
      'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ],
  },
];
